# Generated by Django 5.2.5 on 2025-08-31 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSpotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('spotify_url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('spotify_url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Recco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_spotify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_spotify', to='myplaylist.playlistspotify')),
            ],
        ),
        migrations.CreateModel(
            name='ReccoTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_spotify', to='myplaylist.track')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouriter', to=settings.AUTH_USER_MODEL)),
                ('recco_tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reccomended_tracks', to='myplaylist.reccotracks')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSearched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_spotify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_searched', to='myplaylist.playlistspotify')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_searched', to='myplaylist.track')),
            ],
        ),
    ]
