# Generated by Django 5.2.5 on 2025-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistspotify',
            name='description',
        ),
        migrations.AddField(
            model_name='playlistspotify',
            name='spotify_id',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
