# Generated by Django 5.2.6 on 2025-09-07 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0002_remove_playlistspotify_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistspotify',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
