# Generated by Django 5.2.6 on 2025-09-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0003_playlistspotify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reccotracks',
            name='user',
        ),
        migrations.AddField(
            model_name='recco',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reccotracks',
            name='recco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reccomendation', to='myplaylist.recco'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
