# Generated by Django 5.2.6 on 2025-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0004_remove_reccotracks_user_recco_is_favourite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistspotify',
            name='total_tracks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
