# Generated by Django 5.2.6 on 2025-10-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0005_playlistspotify_total_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistspotify',
            name='total_tracks',
        ),
    ]
