# Generated by Django 5.2.6 on 2025-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0006_remove_playlistspotify_total_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
