# Generated by Django 5.2.6 on 2025-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaylist', '0007_track_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistspotify',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', to='myplaylist.track'),
        ),
        migrations.DeleteModel(
            name='PlaylistSearched',
        ),
    ]
